name: open_weather_client
description: Unofficial OpenWeather package for Current and Forecast weather data.
version: 2.0.0
homepage: 'https://github.com/csongorkeller/flutter_open_weather_package'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  transparent_image: ^2.0.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
